[build]
publish = "."
command = """
export PLAYWRIGHT_BROWSERS_PATH=0
pip install --no-cache-dir -r requirements.txt
python -m playwright install chromium
"""

[build.environment]
PYTHON_VERSION = "3.11"

[functions]
directory = "netlify/functions"
