[build]
publish = "."
command = "npm ci"

[build.environment]
NODE_VERSION = "20"

[functions]
directory = "netlify/functions"
node_bundler = "esbuild"

external_node_modules = ["@sparticuz/chromium", "puppeteer-core"]
included_files = ["node_modules/@sparticuz/chromium/**"]