[build]
publish = "."
command = "PLAYWRIGHT_BROWSERS_PATH=0 npm ci && npx playwright install chromium"

[build.environment]
NODE_VERSION = "20"
PLAYWRIGHT_BROWSERS_PATH = "0"

[functions]
directory = "netlify/functions"
node_bundler = "esbuild"
included_files = ["node_modules/playwright/.local-browsers/**"]
