[build]
publish = "."
command = "npm ci"

[build.environment]
NODE_VERSION = "20"

[functions]
directory = "netlify/functions"
node_bundler = "esbuild"

# No included_files needed. No PLAYWRIGHT_BROWSERS_PATH needed.